rclone:
  stats: 5s
  live_rotate: true
  service_account_remotes:
    '$HOME/easyclone/accounts':
      - src
      - dst
  global_params:
    default:
      copy:
        - '--fast-list'
        - '--drive-server-side-across-configs'
        - '--ignore-existing'
        - '--drive-acknowledge-abuse'
        - '--drive-keep-revision-forever'
        - '--stats=1s'
        - '--stats-one-line'
        - '-vP'
        - '--drive-chunk-size 128M'
        - '--transfers=16'
        - '--checkers=32'
        - '--log-file $HOME/easyclone/log.txt'
      sync:
        - '--fast-list'
        - '--drive-server-side-across-configs'
        - '--drive-acknowledge-abuse'
        - '--drive-keep-revision-forever'
        - '--stats=1s'
        - '--stats-one-line'
        - '-vP'
        - '--drive-chunk-size 128M'
        - '--transfers=16'
        - '--checkers=32'
        - '--log-file $HOME/easyclone/log.txt'
      dedupe:
        - '--verbose=2'
